# Generated by Django 5.0.1 on 2024-02-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_applyleave_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('fullname', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=256)),
                ('phone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.CharField(default='', max_length=30),
        ),
    ]
