# Generated by Django 5.0.1 on 2024-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_moderator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='moderator',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='moderator',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='moderator',
            name='dob',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='moderator',
            name='role',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
