# Generated by Django 5.0.1 on 2024-02-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_fullname_manager_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='id',
        ),
        migrations.AlterField(
            model_name='moderator',
            name='email',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
