# Generated by Django 5.0.1 on 2024-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_remove_manager_password_remove_manager_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="id",
        ),
        migrations.AlterField(
            model_name="manager",
            name="email",
            field=models.CharField(
                default="", max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
