# Generated by Django 5.0.1 on 2024-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_manager_id_alter_manager_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="applied_leave",
            field=models.IntegerField(default=0),
        ),
    ]
