# Generated by Django 5.0.1 on 2024-02-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_applyleave_fromdate_alter_applyleave_todate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyleave",
            name="verified",
            field=models.CharField(default="Pending", max_length=16),
        ),
    ]
