# Generated by Django 5.0.1 on 2024-02-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_applyleave_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="leave_balance",
            field=models.IntegerField(default=30),
        ),
    ]
