# Generated by Django 5.0.1 on 2024-02-12 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_user_leave_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="applied_leave",
        ),
    ]
